christ-the-savior:
    composer: "Dan Schutte"
    kyrie: https://youtu.be/-WKUvor5b0U?list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
    gloria: https://www.youtube.com/watch?v=UwHpbRNYDyw&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
    holy: https://www.youtube.com/watch?v=a7RAweDJUPA&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
    memorial-acclamation-a: https://www.youtube.com/watch?v=tNKvk9Kn70Y&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
    memorial-acclamation-b: https://www.youtube.com/watch?v=nsGftHkvoHk&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
    memorial-acclamation-c: https://www.youtube.com/watch?v=pNoteywgi6M&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
    amen: https://www.youtube.com/watch?v=iSaIKVjsEjk&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
    lamb-of-god: https://www.youtube.com/watch?v=_1_sN3o9f0c&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
christmas-carol-mass:
    composer: "Kevin Weed"
    kyrie-ver1: https://youtu.be/iYYPSiyZO1I?t=0
    kyrie-ver2: https://youtu.be/iYYPSiyZO1I?t=41
    gloria: https://youtu.be/iYYPSiyZO1I?t=82
    holy: https://youtu.be/iYYPSiyZO1I?t=423
    memorial-acclamation-a: https://youtu.be/iYYPSiyZO1I?t=464
    memorial-acclamation-b: https://youtu.be/iYYPSiyZO1I?t=485
    memorial-acclamation-c: https://youtu.be/iYYPSiyZO1I?t=532
    amen: https://youtu.be/iYYPSiyZO1I?t=557
    lamb-of-god: https://youtu.be/iYYPSiyZO1I?t=601
community-mass:
    composer: "Richard Proulx"
    kyrie: https://www.youtube.com/watch?v=B7mQdBhx6Wk
    gloria: https://www.youtube.com/watch?v=T4jhzzrGQpA
    holy: https://www.youtube.com/watch?v=eurc_bUAU_s
    memorial-acclamation-a: https://www.youtube.com/watch?v=rAamLDXQHn8
    memorial-acclamation-b: https://www.youtube.com/watch?v=C0LSbkbOsnQ
    memorial-acclamation-c: https://www.youtube.com/watch?v=oY8VIwxFeQM
    amen: https://www.youtube.com/watch?v=KL83buptUe0
    lamb-of-god: https://www.youtube.com/watch?v=34Nfogq8vM4
heritage-mass:
    composer: "Owen Alstott"
    kyrie: https://www.youtube.com/watch?v=YX6cZ8uEP6A
    gloria: https://youtu.be/tukrgUdjIWU?t=27
    holy: https://www.youtube.com/watch?v=h0gXURFOhyo
    memorial-acclamation-a: https://www.youtube.com/watch?v=g4alz7JVzWM
    memorial-acclamation-b: https://www.youtube.com/watch?v=tKUaBySOq2g
    memorial-acclamation-c: https://www.youtube.com/watch?v=7zXS_mbTDCo
    amen: https://www.youtube.com/watch?v=XpEK_3j3GMY
    lamb-of-god: https://www.youtube.com/watch?v=LQzlBbf3TZo
mass-of-angels-and-saints:
    composer: "Steven Janco"
    kyrie: https://youtu.be/79WlqnjP560?t=5
    gloria: https://youtu.be/79WlqnjP560?t=225
    gospel-acclamation: https://youtu.be/79WlqnjP560?t=400
    holy: https://youtu.be/79WlqnjP560?t=660
    memorial-acclamation-a: https://youtu.be/79WlqnjP560?t=732
    memorial-acclamation-b: https://youtu.be/79WlqnjP560?t=765
    memorial-acclamation-c: https://youtu.be/79WlqnjP560?t=796
    amen: https://youtu.be/79WlqnjP560?t=830
    lamb-of-god: https://youtu.be/79WlqnjP560?t=860
mass-of-charity-and-love:
    composer: "Steve Warner"
    kyrie: https://www.youtube.com/watch?v=5pGeykCfGrI
    gloria: https://youtu.be/pOMPnT6mDeA?list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE
    holy: https://www.youtube.com/watch?v=E_6AglLosIM&list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE&index=3
    memorial-acclamation-a: https://www.youtube.com/watch?v=Y4nazAErY_U&list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE&index=4
    memorial-acclamation-b: https://www.youtube.com/watch?v=fuFdg8POL58&list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE&index=5
    memorial-acclamation-c: https://www.youtube.com/watch?v=9NFScdaoZIs&list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE&index=6
    amen: https://www.youtube.com/watch?v=dfcC-EPF-vQ&list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE&index=7
    lamb-of-god: https://www.youtube.com/watch?v=G5JqIFGASxY&t=92s
mass-of-creation:
    composer: "Marty Haugen"
    kyrie: https://www.youtube.com/watch?v=LfvN8SUFg8Q
    gloria: https://www.youtube.com/watch?v=AK0AV71eRuU
    holy: https://www.youtube.com/watch?v=2nwTK9YKWWo
    memorial-acclamation-a: https://www.youtube.com/watch?v=MaPV39uou1I
    memorial-acclamation-b: https://www.youtube.com/watch?v=cBApgcKhJo0
    memorial-acclamation-c: https://www.youtube.com/shorts/nbCPp3KauTI
    amen: https://www.youtube.com/watch?v=8drMbyPFlPU
    lamb-of-god: https://www.youtube.com/watch?v=_KlqHDoGLzE
mass-of-joy-and-peace:
    composer: "Tony Alonso"
    kyrie: https://www.youtube.com/watch?v=rWeUZPRMhXY
    gloria: https://www.youtube.com/watch?v=vJjPFsepCRc
    holy: https://www.youtube.com/watch?v=QTrOh1eDE9E
    memorial-acclamation-a: https://www.youtube.com/watch?v=zWHX-Wyauf0
    memorial-acclamation-b: https://youtu.be/GwuuUpEc32s?list=OLAK5uy_n2dwc8jyPK_I0YkaCg79U_wL1ppods7hk
    memorial-acclamation-c: https://youtu.be/vPUTgTDxGdE?list=OLAK5uy_n2dwc8jyPK_I0YkaCg79U_wL1ppods7hk
    amen: https://www.youtube.com/watch?v=pDYVSZFUudA
    lamb-of-god: https://www.youtube.com/watch?v=qI61AEr8SHs
missa-emmanuel:
    composer: "Richard Proulx"
    kyrie: https://www.youtube.com/watch?v=2Um3tExTJKQ
    holy: https://www.youtube.com/watch?v=WfWjmrnMEeU
    memorial-acclamation-a: https://youtu.be/85vqMXdbkbM
    memorial-acclamation-b: https://www.youtube.com/watch?v=Q-RQUqJKb4U
    memorial-acclamation-c: https://www.youtube.com/watch?v=HsCJcnonAGc
    amen: https://youtu.be/oiqqBD4bqKo
    lamb-of-god: https://youtu.be/iZw5bAd2YYA
a-christmas-gloria: https://www.youtube.com/watch?v=ERmvcErugvs
celtic-alleluia: https://www.youtube.com/watch?v=cK9QUfDQq0g
chant-mass:
    kyrie-mode-iii: https://www.youtube.com/watch?v=DER_yA-lPGE
    alleluia-mode-vi: https://www.youtube.com/watch?v=v7s0Rb0I9GE
congregational-mass:
    composer: "John Lee"
    gloria: https://www.youtube.com/watch?v=OXzMRQ8sp-c
festival-alleluia: https://www.youtube.com/watch?v=YhPpi6J4TyQ
new-mass-for-congregations: https://www.youtube.com/watch?v=mZcuyarYHlE