# Mass of Christ the Savior (Dan Schutte)
mass-of-christ-the-savior-kyrie:
    original_title: 'Mass of Christ the Savior: Kyrie'
    number: NA
    url: https://youtu.be/-WKUvor5b0U?list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
mass-of-christ-the-savior-gloria:
    original_title: 'Mass of Christ the Savior: Gloria'
    number: NA
    url: https://www.youtube.com/watch?v=UwHpbRNYDyw&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
mass-of-christ-the-savior-holy:
    original_title: 'Mass of Christ the Savior: Holy'
    number: NA
    url: https://www.youtube.com/watch?v=a7RAweDJUPA&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
mass-of-christ-the-savior-memorial-acclamation-a:
    original_title: 'Mass of Christ the Savior: Memorial Acclamation A'
    number: NA
    url: https://www.youtube.com/watch?v=tNKvk9Kn70Y&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
mass-of-christ-the-savior-memorial-acclamation-b:
    original_title: 'Mass of Christ the Savior: Memorial Acclamation B'
    number: NA
    url: https://www.youtube.com/watch?v=nsGftHkvoHk&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
mass-of-christ-the-savior-memorial-acclamation-c:
    original_title: 'Mass of Christ the Savior: Memorial Acclamation C'
    number: NA
    url: https://www.youtube.com/watch?v=pNoteywgi6M&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
mass-of-christ-the-savior-amen:
    original_title: 'Mass of Christ the Savior: Amen'
    number: NA
    url: https://www.youtube.com/watch?v=iSaIKVjsEjk&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
mass-of-christ-the-savior-lamb-of-god:
    original_title: 'Mass of Christ the Savior: Lamb of God'
    number: NA
    url: https://www.youtube.com/watch?v=_1_sN3o9f0c&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ

# Cantus Missae (Chant Mass)
# Multiple formats to support lookup automation
cantus-missae-kyrie:
    original_title: Kýrie
    number: 301
    url: https://www.youtube.com/watch?v=9hrbge-40kw

cantus-missae-gloria:
    original_title: Glória
    number: 302
    url: https://www.youtube.com/watch?v=JM6qmf_C7pU

cantus-missae-a-sanctus:
    original_title: Sanctus (A)
    number: 308
    url: https://www.youtube.com/watch?v=0lXqNnO92wA

cantus-missae-b-sanctus-b:
    original_title: Sanctus (B)
    number: 308
    url: https://www.youtube.com/watch?v=vfDwbeFKoKc

cantus-missae-memorial-acclamation-a:
    original_title: Memorial Acclamation A
    number: 309
    url: NA

cantus-missae-memorial-acclamation-b:
    original_title: Memorial Acclamation B
    number: 309
    url: NA

cantus-missae-a-agnus-dei:
    original_title: Agnus Dei (A)
    number: 313
    url: https://www.youtube.com/watch?v=290y-xaTA3s

cantus-missae-b-agnus-dei:
    original_title: Agnus Dei (B)
    number: 313
    url: https://www.youtube.com/watch?v=JgVQ0SHPeno

cantus-missae-a-holy:
    original_title: Sanctus (A)
    number: 308
    url: https://www.youtube.com/watch?v=0lXqNnO92wA

cantus-missae-b-holy:
    original_title: Sanctus (B)
    number: 308
    url: https://www.youtube.com/watch?v=vfDwbeFKoKc

cantus-missae-memorial-acclamation-a:
    original_title: Memorial Acclamation A
    number: 309
    url: NA

cantus-missae-memorial-acclamation-b:
    original_title: Memorial Acclamation B
    number: 309
    url: NA

cantus-missae-a-lamb-of-god:
    original_title: Agnus Dei (A)
    number: 313
    url: https://www.youtube.com/watch?v=290y-xaTA3s

cantus-missae-b-lamb-of-god:
    original_title: Agnus Dei (B)
    number: 313
    url: https://www.youtube.com/watch?v=JgVQ0SHPeno

# Christmas Carol Mass (Kevin Weed)
christmas-carol-mass-kyrie-ver1:
    original_title: 'Christmas Carol Mass: Kyrie version 1'
    number: NA
    url: https://youtu.be/iYYPSiyZO1I?t=0
christmas-carol-mass-kyrie-ver2:
    original_title: 'Christmas Carol Mass: Kyrie version 2'
    number: NA
    url: https://youtu.be/iYYPSiyZO1I?t=41
christmas-carol-mass-gloria:
    original_title: 'Christmas Carol Mass: Gloria'
    number: NA
    url: https://youtu.be/iYYPSiyZO1I?t=82
christmas-carol-mass-holy:
    original_title: 'Christmas Carol Mass: Holy'
    number: NA
    url: https://youtu.be/iYYPSiyZO1I?t=423
christmas-carol-mass-memorial-acclamation-a:
    original_title: 'Christmas Carol Mass: Memorial Acclamation A'
    number: NA
    url: https://youtu.be/iYYPSiyZO1I?t=464
christmas-carol-mass-memorial-acclamation-b:
    original_title: 'Christmas Carol Mass: Memorial Acclamation B'
    number: NA
    url: https://youtu.be/iYYPSiyZO1I?t=485
christmas-carol-mass-memorial-acclamation-c:
    original_title: 'Christmas Carol Mass: Memorial Acclamation C'
    number: NA
    url: https://youtu.be/iYYPSiyZO1I?t=532
christmas-carol-mass-amen:
    original_title: 'Christmas Carol Mass: Amen'
    number: NA
    url: https://youtu.be/iYYPSiyZO1I?t=557
christmas-carol-mass-lamb-of-god:
    original_title: 'Christmas Carol Mass: Lamb of God'
    number: NA
    url: https://youtu.be/iYYPSiyZO1I?t=601

# Community Mass (Richard Proulx)
a-community-mass-kyrie:
    original_title: 'Community Mass: Kyrie'
    number: NA
    url: https://www.youtube.com/watch?v=B7mQdBhx6Wk
a-community-mass-gloria:
    original_title: 'Community Mass: Gloria'
    number: NA
    url: https://www.youtube.com/watch?v=T4jhzzrGQpA
a-community-mass-holy:
    original_title: 'Community Mass: Holy'
    number: 370
    url: https://www.youtube.com/watch?v=eurc_bUAU_s
a-community-mass-memorial-acclamation-a:
    original_title: 'Community Mass: Memorial Acclamation A'
    number: 371
    url: https://www.youtube.com/watch?v=rAamLDXQHn8
a-community-mass-memorial-acclamation-b:
    original_title: 'Community Mass: Memorial Acclamation B'
    number: 373
    url: https://www.youtube.com/watch?v=C0LSbkbOsnQ
a-community-mass-memorial-acclamation-c:
    original_title: 'Community Mass: Memorial Acclamation C'
    number: NA
    url: https://www.youtube.com/watch?v=oY8VIwxFeQM
a-community-mass-amen:
    original_title: 'Community Mass: Amen'
    number: 372
    url: https://www.youtube.com/watch?v=KL83buptUe0
a-community-mass-lamb-of-god:
    original_title: 'Community Mass: Lamb of God'
    number: 389
    url: https://www.youtube.com/watch?v=34Nfogq8vM4

# Heritage Mass (Owen Alstott)
heritage-mass-kyrie:
    original_title: 'Heritage Mass: Kyrie'
    number: NA
    url: https://www.youtube.com/watch?v=YX6cZ8uEP6A
heritage-mass-gloria:
    original_title: 'Heritage Mass: Gloria'
    number: NA
    url: https://youtu.be/tukrgUdjIWU?t=27
heritage-mass-holy:
    original_title: 'Heritage Mass: Holy'
    number: NA
    url: https://www.youtube.com/watch?v=h0gXURFOhyo
heritage-mass-memorial-acclamation-a:
    original_title: 'Heritage Mass: Memorial Acclamation A'
    number: NA
    url: https://www.youtube.com/watch?v=g4alz7JVzWM
heritage-mass-memorial-acclamation-b:
    original_title: 'Heritage Mass: Memorial Acclamation B'
    number: NA
    url: https://www.youtube.com/watch?v=tKUaBySOq2g
heritage-mass-memorial-acclamation-c:
    original_title: 'Heritage Mass: Memorial Acclamation C'
    number: NA
    url: https://www.youtube.com/watch?v=7zXS_mbTDCo
heritage-mass-amen:
    original_title: 'Heritage Mass: Amen'
    number: NA
    url: https://www.youtube.com/watch?v=XpEK_3j3GMY
heritage-mass-lamb-of-god:
    original_title: 'Heritage Mass: Lamb of God'
    number: NA
    url: https://www.youtube.com/watch?v=LQzlBbf3TZo

# Mass of the Angels and Saints (Steven Janco)
mass-of-the-angels-and-saints-kyrie:
    original_name: 'Mass of the Angels and Saints: Kyrie'
    number: NA
    url: https://youtu.be/79WlqnjP560?t=5
mass-of-the-angels-and-saints-gloria:
    original_name: 'Mass of the Angels and Saints: Gloria'
    number: NA
    url: https://youtu.be/79WlqnjP560?t=225
mass-of-the-angels-and-saints-gospel-acclamation:
    original_name: 'Mass of the Angels and Saints: Gospel Acclamation'
    number: NA
    url: https://youtu.be/79WlqnjP560?t=400
mass-of-the-angels-and-saints-holy:
    original_name: 'Mass of the Angels and Saints: Holy'
    number: 375
    url: https://youtu.be/79WlqnjP560?t=660
mass-of-the-angels-and-saints-memorial-acclamation-a:
    original_name: 'Mass of the Angels and Saints: Memorial Acclamation A'
    number: NA
    url: https://youtu.be/79WlqnjP560?t=732
mass-of-the-angels-and-saints-memorial-acclamation-b:
    original_name: 'Mass of the Angels and Saints: Memorial Acclamation B'
    number: NA
    url: https://youtu.be/79WlqnjP560?t=765
mass-of-the-angels-and-saints-memorial-acclamation-c:
    original_name: 'Mass of the Angels and Saints: Memorial Acclamation C'
    number: 376
    url: https://youtu.be/79WlqnjP560?t=796
mass-of-the-angels-and-saints-amen:
    original_name: 'Mass of the Angels and Saints: Amen'
    number: 377
    url: https://youtu.be/79WlqnjP560?t=830
mass-of-the-angels-and-saints-lamb-of-god:
    original_name: 'Mass of the Angels and Saints: Lamb of God'
    number: 388
    url: https://youtu.be/79WlqnjP560?t=860

# Mass of Charity and Love (Steven Warner)
mass-of-charity-and-love-kyrie:
    original_title: 'Mass of Charity and Love: Kyrie'
    number: NA
    url: https://www.youtube.com/watch?v=5pGeykCfGrI
mass-of-charity-and-love-gloria:
    original_title: 'Mass of Charity and Love: Gloria'
    number: NA
    url: https://youtu.be/pOMPnT6mDeA?list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE
mass-of-charity-and-love-holy:
    original_title: 'Mass of Charity and Love: Holy'
    number: NA
    url: https://www.youtube.com/watch?v=E_6AglLosIM&list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE&index=3
mass-of-charity-and-love-memorial-acclamation-a:
    original_title: 'Mass of Charity and Love: Memorial Acclamation A'
    number: NA
    url: https://www.youtube.com/watch?v=Y4nazAErY_U&list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE&index=4
mass-of-charity-and-love-memorial-acclamation-b:
    original_title: 'Mass of Charity and Love: Memorial Acclamation B'
    number: NA
    url: https://www.youtube.com/watch?v=fuFdg8POL58&list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE&index=5
mass-of-charity-and-love-memorial-acclamation-c:
    original_title: 'Mass of Charity and Love: Memorial Acclamation C'
    number: NA
    url: https://www.youtube.com/watch?v=9NFScdaoZIs&list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE&index=6
mass-of-charity-and-love-amen:
    original_title: 'Mass of Charity and Love: Amen'
    number: NA
    url: https://www.youtube.com/watch?v=dfcC-EPF-vQ&list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE&index=7
mass-of-charity-and-love-lamb-of-god:
    original_title: 'Mass of Charity and Love: Lamb of God'
    number: NA
    url: https://www.youtube.com/watch?v=G5JqIFGASxY&t=92s

# Mass of Creation (Marty Haugen)
mass-of-creation-kyrie:
    original_title: 'Mass of Creation: Kyrie'
    number: 192
    url: https://www.youtube.com/watch?v=LfvN8SUFg8Q
mass-of-creation-gloria:
    original_title: 'Mass of Creation: Gloria'
    number: 193
    url: https://www.youtube.com/watch?v=AK0AV71eRuU
mass-of-creation-holy:
    original_title: 'Mass of Creation: Holy'
    number: 198
    url: https://www.youtube.com/watch?v=2nwTK9YKWWo
mass-of-creation-memorial-acclamation-a:
    original_title: 'Mass of Creation: Memorial Acclamation A'
    number: 199
    url: https://www.youtube.com/watch?v=MaPV39uou1I
mass-of-creation-memorial-acclamation-b:
    original_title: 'Mass of Creation: Memorial Acclamation B'
    number: 200
    url: https://www.youtube.com/watch?v=cBApgcKhJo0
mass-of-creation-memorial-acclamation-c:
    original_title: 'Mass of Creation: Memorial Acclamation C'
    number: 201
    url: https://www.youtube.com/shorts/nbCPp3KauTI
mass-of-creation-amen:
    original_title: 'Mass of Creation: Amen'
    number: 202
    url: https://www.youtube.com/watch?v=8drMbyPFlPU
mass-of-creation-lamb-of-god:
    original_title: 'Mass of Creation: Lamb of God'
    number: 204
    url: https://www.youtube.com/watch?v=_KlqHDoGLzE

# Mass of Joy and Peace (Tony Alonso)
mass-of-joy-and-peace-kyrie:
    original_title: 'Mass of Joy and Peace: Kyrie'
    number: 206
    url: https://www.youtube.com/watch?v=rWeUZPRMhXY
mass-of-joy-and-peace-gloria:
    original_title: 'Mass of Joy and Peace: Gloria'
    number: 207
    url: https://www.youtube.com/watch?v=vJjPFsepCRc
mass-of-joy-and-peace-holy:
    original_title: 'Mass of Joy and Peace: Holy'
    number: 211
    url: https://www.youtube.com/watch?v=QTrOh1eDE9E
mass-of-joy-and-peace-memorial-acclamation-a:
    original_title: 'Mass of Joy and Peace: Memorial Acclamation A'
    number: 212
    url: https://www.youtube.com/watch?v=zWHX-Wyauf0
mass-of-joy-and-peace-memorial-acclamation-b:
    original_title: 'Mass of Joy and Peace: Memorial Acclamation B'
    number: 213
    url: https://youtu.be/GwuuUpEc32s?list=OLAK5uy_n2dwc8jyPK_I0YkaCg79U_wL1ppods7hk
mass-of-joy-and-peace-memorial-acclamation-c:
    original_title: 'Mass of Joy and Peace: Memorial Acclamation C'
    number: 214
    url: https://youtu.be/vPUTgTDxGdE?list=OLAK5uy_n2dwc8jyPK_I0YkaCg79U_wL1ppods7hk
mass-of-joy-and-peace-amen:
    original_title: 'Mass of Joy and Peace: Amen'
    number: 215
    url: https://www.youtube.com/watch?v=pDYVSZFUudA
mass-of-joy-and-peace-lamb-of-god:
    original_title: 'Mass of Joy and Peace: Lamb of God'
    number: 216
    url: https://www.youtube.com/watch?v=qI61AEr8SHs

# Missa Emmanuel (Richard Proulx)
missa-emmanuel-kyrie:
    original_title: 'Missa Emmanuel: Kyrie'
    number: NA
    url: https://www.youtube.com/watch?v=2Um3tExTJKQ
missa-emmanuel-holy:
    original_title: 'Missa Emmanuel: Holy'
    number: 358
    url: https://www.youtube.com/watch?v=WfWjmrnMEeU
missa-emmanuel-memorial-acclamation-a:
    original_title: 'Missa Emmanuel: Memorial Acclamation A'
    number: 359
    url: https://youtu.be/85vqMXdbkbM
missa-emmanuel-memorial-acclamation-b:
    original_title: 'Missa Emmanuel: Memorial Acclamation B'
    number: NA
    url: https://www.youtube.com/watch?v=Q-RQUqJKb4U
missa-emmanuel-memorial-acclamation-c:
    original_title: 'Missa Emmanuel: Memorial Acclamation C'
    number: NA
    url: https://www.youtube.com/watch?v=HsCJcnonAGc
missa-emmanuel-amen:
    original_title: 'Missa Emmanuel: Amen'
    number: 360
    url: https://youtu.be/oiqqBD4bqKo
missa-emmanuel-lamb-of-god:
    original_title: 'Missa Emmanuel: Lamb of God'
    number: NA
    url: https://youtu.be/iZw5bAd2YYA

# Mass of St. Dymphna
mass-of-st-dymphna-gloria:
    original_title: 'Mass of St. Dymphna: Gloria'
    number: NA
    url: https://musicministry.github.io/stegbert/stdymphna.html
    local_path: ../_audio/st-dymphna-gloria.mp3

mass-of-st-dymphna-holy:
    original_title: 'Mass of St. Dymphna: Holy'
    number: NA
    url: https://musicministry.github.io/stegbert/stdymphna.html
    local_path: ../_audio/st-dymphna-holy.mp3

mass-of-st-dymphna-memorial-acclamation-a:
    original_title: 'Mass of St. Dymphna: Memorial Acclamation A'
    number: NA
    url: https://musicministry.github.io/stegbert/stdymphna.html
    local_path: ../_audio/st-dymphna-memaccA.mp3

mass-of-st-dymphna-amen:
    original_title: 'Mass of St. Dymphna: Amen'
    number: NA
    url: https://musicministry.github.io/stegbert/stdymphna.html
    local_path: ../_audio/st-dymphna-amen.mp3

mass-of-st-dymphna-lamb-of-god:
    original_title: 'Mass of St. Dymphna: Lamb of God'
    number: NA
    url: https://musicministry.github.io/stegbert/stdymphna.html
    local_path: ../_audio/st-dymphna-lambofgod.mp3

# Others
chant-mass-mode-iii-kyrie:
    original_title: 'Chant Mode III: Kyrie'
    number: 169
    url: https://www.youtube.com/watch?v=DER_yA-lPGE

chant-mass-mode-vi-alleluia:
    original_title: 'Chant Mode VI: Alleluia'
    number: 326
    url: https://www.youtube.com/watch?v=v7s0Rb0I9GE

a-christmas-gloria-gloria:
    original_title: 'A Christmas Gloria'
    number: NA
    url: https://www.youtube.com/watch?v=ERmvcErugvs

congregational-mass-gloria:
    original_title: 'Congregational Mass: Gloria'
    number: 322
    url: https://www.youtube.com/watch?v=OXzMRQ8sp-c

new-mass-for-congregations-gloria:
    original_title: 'A New Mass for Congregations: Gloria'
    number: 319
    url: https://www.youtube.com/watch?v=mZcuyarYHlE

celtic-alleluia:
    original_title: 'Celtic Alleluia'
    number: 334
    url: https://www.youtube.com/watch?v=cK9QUfDQq0g

festival-alleluia:
    original_title: 'Festival Alleluia'
    number: NA
    url: https://www.youtube.com/watch?v=YhPpi6J4TyQ

litany-of-the-saints-becker:
    original_title: Litany of the Saints (Becker)
    composer: John Becker
    number: NA
    url: https://www.youtube.com/watch?v=kJdcehJ2rKc
