# Mass of Christ the Savior (Dan Schutte)
christ-the-savior-kyrie: https://youtu.be/-WKUvor5b0U?list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
christ-the-savior-gloria: https://www.youtube.com/watch?v=UwHpbRNYDyw&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
christ-the-savior-holy: https://www.youtube.com/watch?v=a7RAweDJUPA&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
christ-the-savior-memorial-acclamation-a: https://www.youtube.com/watch?v=tNKvk9Kn70Y&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
christ-the-savior-memorial-acclamation-b: https://www.youtube.com/watch?v=nsGftHkvoHk&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
christ-the-savior-memorial-acclamation-c: https://www.youtube.com/watch?v=pNoteywgi6M&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
christ-the-savior-amen: https://www.youtube.com/watch?v=iSaIKVjsEjk&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ
christ-the-savior-lamb-of-god: https://www.youtube.com/watch?v=_1_sN3o9f0c&list=OLAK5uy_kQuUStdQWJnmXAvXIIF4QNXVjeqo9r1KQ

# Christmas Carol Mass (Kevin Weed)
christmas-carol-mass-kyrie-ver1: https://youtu.be/iYYPSiyZO1I?t=0
christmas-carol-mass-kyrie-ver2: https://youtu.be/iYYPSiyZO1I?t=41
christmas-carol-mass-gloria: https://youtu.be/iYYPSiyZO1I?t=82
christmas-carol-mass-holy: https://youtu.be/iYYPSiyZO1I?t=423
christmas-carol-mass-memorial-acclamation-a: https://youtu.be/iYYPSiyZO1I?t=464
christmas-carol-mass-memorial-acclamation-b: https://youtu.be/iYYPSiyZO1I?t=485
christmas-carol-mass-memorial-acclamation-c: https://youtu.be/iYYPSiyZO1I?t=532
christmas-carol-mass-amen: https://youtu.be/iYYPSiyZO1I?t=557
christmas-carol-mass-lamb-of-god: https://youtu.be/iYYPSiyZO1I?t=601

# Community Mass (Richard Proulx)
community-mass-kyrie: https://www.youtube.com/watch?v=B7mQdBhx6Wk
community-mass-gloria: https://www.youtube.com/watch?v=T4jhzzrGQpA
community-mass-holy: https://www.youtube.com/watch?v=eurc_bUAU_s
community-mass-memorial-acclamation-a: https://www.youtube.com/watch?v=rAamLDXQHn8
community-mass-memorial-acclamation-b: https://www.youtube.com/watch?v=C0LSbkbOsnQ
community-mass-memorial-acclamation-c: https://www.youtube.com/watch?v=oY8VIwxFeQM
community-mass-amen: https://www.youtube.com/watch?v=KL83buptUe0
community-mass-lamb-of-god: https://www.youtube.com/watch?v=34Nfogq8vM4

# Heritage Mass (Owen Alstott)
heritage-mass-kyrie: https://www.youtube.com/watch?v=YX6cZ8uEP6A
heritage-mass-gloria: https://youtu.be/tukrgUdjIWU?t=27
heritage-mass-holy: https://www.youtube.com/watch?v=h0gXURFOhyo
heritage-mass-memorial-acclamation-a: https://www.youtube.com/watch?v=g4alz7JVzWM
heritage-mass-memorial-acclamation-b: https://www.youtube.com/watch?v=tKUaBySOq2g
heritage-mass-memorial-acclamation-c: https://www.youtube.com/watch?v=7zXS_mbTDCo
heritage-mass-amen: https://www.youtube.com/watch?v=XpEK_3j3GMY
heritage-mass-lamb-of-god: https://www.youtube.com/watch?v=LQzlBbf3TZo

# Mass of Angels and Saints (Steven Janco)
mass-of-angels-and-saints-kyrie: https://youtu.be/79WlqnjP560?t=5
mass-of-angels-and-saints-gloria: https://youtu.be/79WlqnjP560?t=225
mass-of-angels-and-saints-gospel-acclamation: https://youtu.be/79WlqnjP560?t=400
mass-of-angels-and-saints-holy: https://youtu.be/79WlqnjP560?t=660
mass-of-angels-and-saints-memorial-acclamation-a: https://youtu.be/79WlqnjP560?t=732
mass-of-angels-and-saints-memorial-acclamation-b: https://youtu.be/79WlqnjP560?t=765
mass-of-angels-and-saints-memorial-acclamation-c: https://youtu.be/79WlqnjP560?t=796
mass-of-angels-and-saints-amen: https://youtu.be/79WlqnjP560?t=830
mass-of-angels-and-saints-lamb-of-god: https://youtu.be/79WlqnjP560?t=860

# Mass of Charity and Love (Steven Warner)
mass-of-charity-and-love-kyrie: https://www.youtube.com/watch?v=5pGeykCfGrI
mass-of-charity-and-love-gloria: https://youtu.be/pOMPnT6mDeA?list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE
mass-of-charity-and-love-holy: https://www.youtube.com/watch?v=E_6AglLosIM&list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE&index=3
mass-of-charity-and-love-memorial-acclamation-a: https://www.youtube.com/watch?v=Y4nazAErY_U&list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE&index=4
mass-of-charity-and-love-memorial-acclamation-b: https://www.youtube.com/watch?v=fuFdg8POL58&list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE&index=5
mass-of-charity-and-love-memorial-acclamation-c: https://www.youtube.com/watch?v=9NFScdaoZIs&list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE&index=6
mass-of-charity-and-love-amen: https://www.youtube.com/watch?v=dfcC-EPF-vQ&list=OLAK5uy_l4fWp74BRiJlYv_ep0IZi2J9yjAxJ3vEE&index=7
mass-of-charity-and-love-lamb-of-god: https://www.youtube.com/watch?v=G5JqIFGASxY&t=92s

# Mass of Creation (Marty Haugen)
mass-of-creation-kyrie: https://www.youtube.com/watch?v=LfvN8SUFg8Q
mass-of-creation-gloria: https://www.youtube.com/watch?v=AK0AV71eRuU
mass-of-creation-holy: https://www.youtube.com/watch?v=2nwTK9YKWWo
mass-of-creation-memorial-acclamation-a: https://www.youtube.com/watch?v=MaPV39uou1I
mass-of-creation-memorial-acclamation-b: https://www.youtube.com/watch?v=cBApgcKhJo0
mass-of-creation-memorial-acclamation-c: https://www.youtube.com/shorts/nbCPp3KauTI
mass-of-creation-amen: https://www.youtube.com/watch?v=8drMbyPFlPU
mass-of-creation-lamb-of-god: https://www.youtube.com/watch?v=_KlqHDoGLzE

# Mass of Joy and Peace (Tony Alonso)
mass-of-joy-and-peace-kyrie: https://www.youtube.com/watch?v=rWeUZPRMhXY
mass-of-joy-and-peace-gloria: https://www.youtube.com/watch?v=vJjPFsepCRc
mass-of-joy-and-peace-holy: https://www.youtube.com/watch?v=QTrOh1eDE9E
mass-of-joy-and-peace-memorial-acclamation-a: https://www.youtube.com/watch?v=zWHX-Wyauf0
mass-of-joy-and-peace-memorial-acclamation-b: https://youtu.be/GwuuUpEc32s?list=OLAK5uy_n2dwc8jyPK_I0YkaCg79U_wL1ppods7hk
mass-of-joy-and-peace-memorial-acclamation-c: https://youtu.be/vPUTgTDxGdE?list=OLAK5uy_n2dwc8jyPK_I0YkaCg79U_wL1ppods7hk
mass-of-joy-and-peace-amen: https://www.youtube.com/watch?v=pDYVSZFUudA
mass-of-joy-and-peace-lamb-of-god: https://www.youtube.com/watch?v=qI61AEr8SHs

# Missa Emmanuel (Richard Proulx)
missa-emmanuel-kyrie: https://www.youtube.com/watch?v=2Um3tExTJKQ
missa-emmanuel-holy: https://www.youtube.com/watch?v=WfWjmrnMEeU
missa-emmanuel-memorial-acclamation-a: https://youtu.be/85vqMXdbkbM
missa-emmanuel-memorial-acclamation-b: https://www.youtube.com/watch?v=Q-RQUqJKb4U
missa-emmanuel-memorial-acclamation-c: https://www.youtube.com/watch?v=HsCJcnonAGc
missa-emmanuel-amen: https://youtu.be/oiqqBD4bqKo
missa-emmanuel-lamb-of-god: https://youtu.be/iZw5bAd2YYA

# Others
chant-mass-mode-iii-kyrie: https://www.youtube.com/watch?v=DER_yA-lPGE
chant-mass-mode-vi-alleluia: https://www.youtube.com/watch?v=v7s0Rb0I9GE

a-christmas-gloria-gloria: https://www.youtube.com/watch?v=ERmvcErugvs

congregational-mass-gloria: https://www.youtube.com/watch?v=OXzMRQ8sp-c
new-mass-for-congregations-gloria: https://www.youtube.com/watch?v=mZcuyarYHlE

celtic-alleluia: https://www.youtube.com/watch?v=cK9QUfDQq0g

festival-alleluia: https://www.youtube.com/watch?v=YhPpi6J4TyQ
